apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentinelops
resources:
  - namespace.yaml
  - timescaledb.yaml
  - redpanda.yaml
  - log-producer.yaml
  - ingestion-go.yaml
  - anomaly-rust.yaml