# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.v1.jsonschema.json
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.v1.jsonschema.json
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - gosec

linters-settings:
  gosec:
    excludes:
      - G404 # math/rand is fine for non-cryptographic simulation use

issues:
  max-issues-per-linter: 0
  max-same-issues: 0